/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TokenInfo = IDL.Record({
  'tokenSupply' : IDL.Nat,
  'websiteUrl' : IDL.Text,
  'telegramUrl' : IDL.Text,
  'twitterUrl' : IDL.Text,
  'tokenSymbol' : IDL.Text,
  'coingeckoUrl' : IDL.Text,
  'contractAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'visit' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TokenInfo = IDL.Record({
    'tokenSupply' : IDL.Nat,
    'websiteUrl' : IDL.Text,
    'telegramUrl' : IDL.Text,
    'twitterUrl' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'coingeckoUrl' : IDL.Text,
    'contractAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'getTokenInfo' : IDL.Func([], [TokenInfo], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'visit' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };